# Generated by Django 4.2.3 on 2024-06-27 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdCategory',
            fields=[
                ('ad_category_id', models.AutoField(db_column='Ad_Category_ID', primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_column='Category_Name', max_length=55)),
            ],
            options={
                'db_table': 'ad_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdReports',
            fields=[
                ('ad_report_id', models.AutoField(db_column='Ad_Report_ID', primary_key=True, serialize=False)),
                ('note_report', models.CharField(db_column='Note_Report', max_length=1000)),
            ],
            options={
                'db_table': 'ad_reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('ad_id', models.AutoField(db_column='Ad_ID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=55)),
                ('ad_status', models.CharField(blank=True, db_column='Ad_STATUS', max_length=10, null=True)),
                ('info', models.CharField(blank=True, db_column='INFO', max_length=1000, null=True)),
                ('add_time', models.DateTimeField(blank=True, db_column='Add_Time', null=True)),
                ('price', models.IntegerField(db_column='Price')),
                ('city_id', models.IntegerField(db_column='City_ID')),
                ('views', models.IntegerField(blank=True, db_column='Views', null=True)),
                ('identifier', models.CharField(blank=True, db_column='Identifier', max_length=8, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='Deleted_at', null=True)),
            ],
            options={
                'db_table': 'ads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdStatus',
            fields=[
                ('ad_status_id', models.AutoField(db_column='Ad_Status_ID', primary_key=True, serialize=False)),
                ('edit_time', models.DateTimeField(blank=True, db_column='Edit_Time', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=10, null=True)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'ad_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.AutoField(db_column='Business_ID', primary_key=True, serialize=False)),
                ('business_name', models.CharField(db_column='Business_Name', max_length=55)),
                ('address', models.CharField(db_column='Address', max_length=255)),
                ('registeration_code', models.CharField(db_column='Registeration_Code', max_length=55, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='Deleted_at', null=True)),
            ],
            options={
                'db_table': 'business',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('business_category_id', models.AutoField(db_column='Business_Category_ID', primary_key=True, serialize=False)),
                ('business_category_name', models.CharField(db_column='Business_Category_Name', max_length=55, unique=True)),
            ],
            options={
                'db_table': 'business_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(db_column='City_ID', primary_key=True, serialize=False)),
                ('city_name', models.CharField(db_column='City_Name', max_length=55)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImgOfAd',
            fields=[
                ('img_id', models.AutoField(db_column='IMG_ID', primary_key=True, serialize=False)),
                ('img_link', models.CharField(db_column='IMG_Link', max_length=255)),
            ],
            options={
                'db_table': 'img_of_ad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('meta_id', models.AutoField(db_column='Meta_ID', primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=55)),
                ('value', models.CharField(max_length=55)),
            ],
            options={
                'db_table': 'meta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.AutoField(db_column='Province_ID', primary_key=True, serialize=False)),
                ('province_name', models.CharField(db_column='Province_Name', max_length=55, unique=True)),
            ],
            options={
                'db_table': 'province',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportKind',
            fields=[
                ('report_kind_id', models.AutoField(db_column='Report_Kind_ID', primary_key=True, serialize=False)),
                ('report_kind_name', models.CharField(db_column='Report_Kind_Name', max_length=55)),
            ],
            options={
                'db_table': 'report_kind',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(db_column='User_ID', primary_key=True, serialize=False)),
                ('user_status', models.CharField(db_column='User_Status', max_length=8)),
                ('first_name', models.CharField(db_column='First_Name', max_length=55)),
                ('last_name', models.CharField(db_column='Last_Name', max_length=55)),
                ('phone_number', models.CharField(db_column='Phone_Number', max_length=55, unique=True)),
                ('email', models.CharField(db_column='Email', max_length=255, unique=True)),
                ('city_id', models.IntegerField(db_column='City_ID')),
                ('profile_img', models.CharField(blank=True, db_column='Profile_IMG', max_length=1000, null=True)),
                ('user_kind', models.CharField(db_column='User_Kind', max_length=1)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdsOfBusiness',
            fields=[
                ('ad', models.OneToOneField(db_column='Ad_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ads.ads')),
            ],
            options={
                'db_table': 'ads_of_business',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdsOfUsers',
            fields=[
                ('ad', models.OneToOneField(db_column='Ad_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ads.ads')),
            ],
            options={
                'db_table': 'ads_of_users',
                'managed': False,
            },
        ),
    ]
